# -*- coding: utf-8 -*-
"""EfficientNetB0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hZEyZ0DIDs-PgLJmUeR1YnS22NJ8Gthq
"""

# ============================================================
# B_0.py - Bone Fracture Detection using EfficientNetB0
# All modifications applied - Uses dataset_split folder
# ============================================================

# ===================== 1. Google Colab Setup =====================
from google.colab import drive
drive.mount('/content/drive')

# ===================== 2. Import Libraries =====================
import tensorflow as tf
import os
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import classification_report, confusion_matrix
import seaborn as sns
import pandas as pd
import random
from PIL import Image

# ===================== 3. Path Configuration =====================
# Main folder: dataset_split contains train, val, test
# NOTE: Update base_path to match your Google Drive structure
base_path = '/content/drive/MyDrive/archive (31)'
data_root_dir = os.path.join(base_path, 'dataset_split')
train_dir = os.path.join(data_root_dir, 'train')
val_dir = os.path.join(data_root_dir, 'val')
test_dir = os.path.join(data_root_dir, 'test')

# ===================== 4. EDA - Class Distribution =====================
class_counts = {}

for class_name in os.listdir(train_dir):
    class_path = os.path.join(train_dir, class_name)
    if os.path.isdir(class_path):
        class_counts[class_name] = len(os.listdir(class_path))

plt.bar(class_counts.keys(), class_counts.values())
plt.title("Class Distribution (Train Set)")
plt.xlabel("Class")
plt.ylabel("Number of Images")
plt.show()

# ===================== 5. EDA - Sample Images =====================
plt.figure(figsize=(10, 5))

for i, class_name in enumerate(os.listdir(train_dir)):
    class_path = os.path.join(train_dir, class_name)
    if not os.path.isdir(class_path):
        continue
    img_name = random.choice(os.listdir(class_path))
    img_path = os.path.join(class_path, img_name)

    img = Image.open(img_path)

    plt.subplot(1, 2, i + 1)
    plt.imshow(img)
    plt.title(class_name)
    plt.axis("off")

plt.show()

# ===================== 6. EDA - Image Dimensions =====================
widths = []
heights = []

for class_name in os.listdir(train_dir):
    class_path = os.path.join(train_dir, class_name)
    if not os.path.isdir(class_path):
        continue

    for img_name in os.listdir(class_path)[:100]:  # sample
        img_path = os.path.join(class_path, img_name)
        try:
            img = Image.open(img_path)
            w, h = img.size
            widths.append(w)
            heights.append(h)
        except:
            continue

plt.hist(widths, bins=20)
plt.title("Width Distribution")
plt.show()

plt.hist(heights, bins=20)
plt.title("Height Distribution")
plt.show()

# ===================== 7. Dataset Split Summary =====================
print("=== Dataset Split Summary ===")
for split_name in ['train', 'val', 'test']:
    split_dir = os.path.join(data_root_dir, split_name)
    for class_name in ['Fractured', 'Non_fractured']:
        class_dir = os.path.join(split_dir, class_name)
        count = len(os.listdir(class_dir))
        print(f"  {split_name}/{class_name}: {count}")

# ===================== 8. Load Data from dataset_split =====================
IMG_SIZE = (224, 224)
BATCH_SIZE = 32
SEED = 42

train_ds = tf.keras.utils.image_dataset_from_directory(
    train_dir,
    seed=SEED,
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE
)

val_ds = tf.keras.utils.image_dataset_from_directory(
    val_dir,
    seed=SEED,
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE
)

test_ds = tf.keras.utils.image_dataset_from_directory(
    test_dir,
    seed=SEED,
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE
)

# Save class names BEFORE pipeline transforms (cache/shuffle/map destroy it)
class_names = train_ds.class_names
print("Class mapping:", class_names)  # Should be ['Fractured', 'Non_fractured']

# ===================== 9. Batch Inspection =====================
for images, labels in train_ds.take(1):
    plt.figure(figsize=(10, 10))
    for i in range(9):
        plt.subplot(3, 3, i + 1)
        plt.imshow(images[i].numpy().astype("uint8"))
        plt.title(labels[i].numpy())
        plt.axis("off")
    plt.show()

# ===================== 10. Sample Fractured Image =====================
img_path = os.path.join(train_dir, 'Fractured', os.listdir(os.path.join(train_dir, 'Fractured'))[0])
img = Image.open(img_path)

plt.imshow(img)
plt.axis("off")
plt.title("Sample Fractured Image from Train Set")
plt.show()

# ===================== 11. Pipeline Optimization =====================
AUTOTUNE = tf.data.AUTOTUNE

train_ds = train_ds.cache().shuffle(1000).prefetch(buffer_size=AUTOTUNE)
val_ds = val_ds.cache().prefetch(buffer_size=AUTOTUNE)
test_ds = test_ds.cache().prefetch(buffer_size=AUTOTUNE)

# ===================== 12. Data Augmentation (Improved) =====================
data_augmentation = tf.keras.Sequential([
    tf.keras.layers.RandomFlip("horizontal"),
    tf.keras.layers.RandomFlip("vertical"),
    tf.keras.layers.RandomRotation(0.2),
    tf.keras.layers.RandomZoom(0.2),
    tf.keras.layers.RandomContrast(0.2),
    tf.keras.layers.RandomBrightness(0.2),
])


def augment(images, labels):
    return data_augmentation(images), labels


train_ds = train_ds.map(augment)

# ===================== 13. Build Model (Improved Head) =====================
base_model = tf.keras.applications.EfficientNetB0(
    include_top=False,
    weights='imagenet',
    input_shape=(224, 224, 3)
)
base_model.trainable = False

x = base_model.output

x = tf.keras.layers.GlobalAveragePooling2D()(x)
x = tf.keras.layers.BatchNormalization()(x)

x = tf.keras.layers.Dense(256, activation='relu')(x)
x = tf.keras.layers.Dropout(0.4)(x)

x = tf.keras.layers.Dense(64, activation='relu')(x)
x = tf.keras.layers.Dropout(0.3)(x)

output = tf.keras.layers.Dense(1, activation='sigmoid')(x)
model = tf.keras.Model(inputs=base_model.input, outputs=output)
model.summary()

# ===================== 14. Compute Class Weights (Dynamic) =====================
# IMPORTANT: image_dataset_from_directory sorts classes ALPHABETICALLY
# So: Fractured = class 0, Non_fractured = class 1
print("Class mapping:", class_names)

train_fractured = len(os.listdir(os.path.join(train_dir, 'Fractured')))
train_non_fractured = len(os.listdir(os.path.join(train_dir, 'Non_fractured')))
total_samples = train_fractured + train_non_fractured

weight_for_0 = total_samples / (2 * train_fractured)       # Fractured (class 0)
weight_for_1 = total_samples / (2 * train_non_fractured)   # Non_fractured (class 1)
class_weight = {0: weight_for_0, 1: weight_for_1}
print(f"Train samples: Fractured={train_fractured}, Non_fractured={train_non_fractured}")
print(f"Class weights: Fractured(0)={weight_for_0:.2f}, Non_fractured(1)={weight_for_1:.2f}")

# ===================== 15. Training Phase 1 (with Callbacks) =====================
early_stopping = tf.keras.callbacks.EarlyStopping(
    monitor='val_loss',
    patience=5,
    restore_best_weights=True
)

reduce_lr = tf.keras.callbacks.ReduceLROnPlateau(
    monitor='val_loss',
    factor=0.5,
    patience=3,
    min_lr=1e-7
)

model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.0001),
    loss='binary_crossentropy',
    metrics=['accuracy']
)

history = model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=30,
    class_weight=class_weight,
    callbacks=[early_stopping, reduce_lr]
)

# ===================== 16. Fine-Tuning (with Callbacks) =====================
base_model.trainable = True

for layer in base_model.layers[:-30]:
    layer.trainable = False

early_stopping_fine = tf.keras.callbacks.EarlyStopping(
    monitor='val_loss',
    patience=3,
    restore_best_weights=True
)

reduce_lr_fine = tf.keras.callbacks.ReduceLROnPlateau(
    monitor='val_loss',
    factor=0.5,
    patience=2,
    min_lr=1e-8
)

model.compile(
    optimizer=tf.keras.optimizers.Adam(1e-5),
    loss='binary_crossentropy',
    metrics=['accuracy']
)

history_fine = model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=10,
    class_weight=class_weight,
    callbacks=[early_stopping_fine, reduce_lr_fine]
)

# ===================== 17. Evaluate on Validation Set =====================
y_true = []
y_pred = []

for images, labels in val_ds:
    preds = model.predict(images)
    preds = (preds > 0.5).astype(int)

    y_true.extend(labels.numpy())
    y_pred.extend(preds.flatten())

print("=== Validation Set Results ===")
print(classification_report(y_true, y_pred))

# ===================== 18. Learning Curves =====================
plt.plot(history.history['loss'], label='train_loss')
plt.plot(history.history['val_loss'], label='val_loss')
plt.legend()
plt.title("Loss")
plt.show()

plt.plot(history.history['accuracy'], label='train_acc')
plt.plot(history.history['val_accuracy'], label='val_acc')
plt.legend()
plt.title("Accuracy")
plt.show()

# ===================== 19. Confusion Matrix =====================
cm = confusion_matrix(y_true, y_pred)
plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues",
            xticklabels=['Non_fractured', 'Fractured'],
            yticklabels=['Non_fractured', 'Fractured'])
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
plt.show()

# ===================== 20. Classification Metrics =====================
report = classification_report(y_true, y_pred, output_dict=True)
df = pd.DataFrame(report).transpose()

df[['precision', 'recall', 'f1-score']].plot(kind='bar', figsize=(10, 6))
plt.title("Classification Metrics")
plt.ylabel("Score")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# ===================== 21. Save Model =====================
model.save("fracture_model_tf.h5")

# ===================== 22. Prediction Function =====================
import cv2


def predict(img_path):
    img = cv2.imread(img_path)
    img = cv2.resize(img, (224, 224))
    img = img / 255.0
    img = np.expand_dims(img, axis=0)

    pred = model.predict(img)[0][0]
    return "Fractured" if pred > 0.5 else "Normal"


# ===================== 23. Evaluate on Test Set =====================
print("Evaluating on Test Dataset...")
y_true_test = []
y_pred_test = []

for images, labels in test_ds:
    preds = model.predict(images)
    preds = (preds > 0.5).astype(int)

    y_true_test.extend(labels.numpy())
    y_pred_test.extend(preds.flatten())

print("=== Test Set Results ===")
print(classification_report(y_true_test, y_pred_test))

