# -*- coding: utf-8 -*-
"""EfficientNetB4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hZEyZ0DIDs-PgLJmUeR1YnS22NJ8Gthq
"""

from google.colab import drive
drive.mount('/content/drive')

# =====================================================================
# CELL 1: Imports & Setup
# =====================================================================
import os
import shutil
import random
import numpy as np
import pandas as pd
import tensorflow as tf
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import seaborn as sns
from sklearn.metrics import (classification_report, confusion_matrix,
                             roc_curve, auc, precision_recall_curve)
from PIL import Image
import nest_asyncio
import warnings
warnings.filterwarnings('ignore')

print("✅ All libraries imported successfully")
print(f"🔢 TensorFlow version: {tf.__version__}")
print(f"🖥️  GPU Available: {tf.config.list_physical_devices('GPU')}")

# =====================================================================
# CELL 2: PATH CONFIGURATION
# =====================================================================
try:
    from google.colab import drive
    print("🚀 Running in Google Colab. Mounting Drive...")
    drive.mount('/content/drive')

    base_path     = '/content/drive/MyDrive/archive (31)'
    FORCE_RETRAIN = False

    if not os.path.exists(base_path):
        print(f"\n❌ ERROR: Path '{base_path}' not found.")
        for folder in os.listdir('/content/drive/MyDrive'):
            print(f"  - {folder}")
        import sys
        sys.exit("ACTION REQUIRED: Fix folder name in 'base_path'.")

    possible_names   = ['datasplit', 'dataset_split', 'data']
    data_folder_name = None
    for name in possible_names:
        if os.path.exists(os.path.join(base_path, name)):
            data_folder_name = name
            break

    if not data_folder_name:
        print(f"❌ ERROR: Could not find data folder (tried: {possible_names})")
        import sys
        sys.exit("ACTION REQUIRED: Ensure your data folder exists.")

    data_root_dir = os.path.join(base_path, data_folder_name)
    print(f"✅ Data folder found: {data_folder_name}")
    nest_asyncio.apply()

except ImportError:
    base_path     = os.path.dirname(os.path.abspath(__file__))
    data_root_dir = os.path.join(base_path, 'datasplit')

# ── Global Paths ──────────────────────────────────────────────────────
train_dir   = os.path.join(data_root_dir, 'train')
val_dir     = os.path.join(data_root_dir, 'val')
test_dir    = os.path.join(data_root_dir, 'test')
MODEL_PATH  = os.path.join(base_path, "fracture_model_b4_final.keras")  # ← .keras أفضل
IMG_SIZE    = (380, 380)
BATCH_SIZE  = 32
EPOCHS      = 20
CLASS_NAMES = ['Fractured', 'Non_fractured']

print(f"\n📁 Paths OK | IMG={IMG_SIZE} | BATCH={BATCH_SIZE} | EPOCHS={EPOCHS}")

# =====================================================================
# CELL 3: DATA UTILITIES
# =====================================================================

def standardize_images(target_dir, target_size=(380, 380)):
    print(f"\n🔄 Standardizing: {target_dir}")
    converted, skipped = 0, 0
    for root, _, files in os.walk(target_dir):
        for file in files:
            if not file.lower().endswith(
                    ('.png', '.jpg', '.jpeg', '.bmp', '.gif', '.webp')):
                continue
            fp = os.path.join(root, file)
            try:
                with Image.open(fp) as img:
                    img      = img.convert('RGB').resize(target_size)
                    new_path = os.path.splitext(fp)[0] + ".jpg"
                    img.save(new_path, "JPEG", quality=95)
                if fp != new_path:
                    os.remove(fp)
                converted += 1
            except Exception as e:
                print(f"  ⚠️ Skipping {file}: {e}")
                skipped += 1
    print(f"  ✅ converted={converted} | skipped={skipped}")


def balance_dataset(target_dir, target_count=1500):
    print(f"\n⚖️  Balancing: {target_dir}  (target={target_count})")
    for cls in CLASS_NAMES:
        cls_path = os.path.join(target_dir, cls)
        if not os.path.exists(cls_path):
            print(f"  ⚠️ Not found: {cls_path}")
            continue
        files = [os.path.join(cls_path, f)
                 for f in os.listdir(cls_path)
                 if f.lower().endswith('.jpg')]
        print(f"  [{cls}] before: {len(files)}")
        if cls == 'Non_fractured' and len(files) > target_count:
            for f in random.sample(files, len(files) - target_count):
                os.remove(f)
        elif cls == 'Fractured' and len(files) < target_count:
            for i in range(target_count - len(files)):
                src  = random.choice(files)
                dest = os.path.join(cls_path, f"aug_{i}_{os.path.basename(src)}")
                shutil.copy2(src, dest)
        print(f"  [{cls}] after : {len(os.listdir(cls_path))}  ✅")


def dataset_stats(directory, label=""):
    print(f"\n📊 Stats — {label}")
    total = 0
    for cls in CLASS_NAMES:
        p = os.path.join(directory, cls)
        if os.path.exists(p):
            n = len(os.listdir(p)); total += n
            print(f"  {cls:<20}: {n:>5}")
    print(f"  {'TOTAL':<20}: {total:>5}")
    return total

# =====================================================================
# CELL 4: CUSTOM CALLBACK
# =====================================================================

class EpochLogger(tf.keras.callbacks.Callback):
    def __init__(self, phase_name="Phase"):
        super().__init__()
        self.phase_name = phase_name
        self.history    = []

    def on_train_begin(self, logs=None):
        print(f"\n{'─'*100}")
        print(f"  {'Epoch':<8} | {'Train Acc':>10} | {'Val Acc':>10} | "
              f"{'Train Loss':>11} | {'Val Loss':>10} | {'LR':>10} | {'Gap':>8} | Status")
        print(f"{'─'*100}")

    def on_epoch_end(self, epoch, logs=None):
        logs    = logs or {}
        tr_acc  = logs.get('accuracy',     0.0)
        vl_acc  = logs.get('val_accuracy', 0.0)
        tr_loss = logs.get('loss',         0.0)
        vl_loss = logs.get('val_loss',     0.0)
        gap     = tr_acc - vl_acc

        try:
            lr = float(tf.keras.backend.get_value(
                       self.model.optimizer.learning_rate))
        except Exception:
            lr = 0.0

        if   gap >  0.10: status = "🔴 OVERFIT"
        elif gap >  0.05: status = "🟡 Mild OVF"
        elif gap < -0.05: status = "🔵 Underfit"
        else:             status = "✅ OK"

        self.history.append(dict(epoch=epoch+1, tr_acc=tr_acc, vl_acc=vl_acc,
                                 tr_loss=tr_loss, vl_loss=vl_loss, gap=gap, lr=lr))
        print(f"  {self.phase_name}-{epoch+1:<4} | {tr_acc:>10.4f} | {vl_acc:>10.4f} | "
              f"{tr_loss:>11.4f} | {vl_loss:>10.4f} | {lr:>10.2e} | {gap:>+8.4f} | {status}")

    def on_train_end(self, logs=None):
        print(f"{'─'*100}")
        if not self.history: return
        max_gap = max(r['gap'] for r in self.history)
        best_vl = max(r['vl_acc'] for r in self.history)
        best_ep = next(r['epoch'] for r in self.history if r['vl_acc'] == best_vl)
        print(f"\n  📌 [{self.phase_name}] Best Val Acc: {best_vl:.4f} (ep {best_ep}) | "
              f"Max Gap: {max_gap:+.4f} ", end="")
        if   max_gap > 0.10: print("→ 🔴 Overfitting!")
        elif max_gap > 0.05: print("→ 🟡 Mild Overfitting")
        else:                print("→ ✅ Good generalisation")

# =====================================================================
# CELL 5: BUILD MODEL — Functional API (يحل مشكلة BatchNorm)
# =====================================================================

def build_model():
    """
    ✅ إصلاح رئيسي: Functional API مع training=False للـ base model
    هذا يحل مشكلة BatchNorm في EfficientNet عند التجميد —
    يضمن أن BN تعمل في inference mode بشكل صريح،
    فتتطابق نتائج التدريب مع التسريب.

    ✅ إصلاح ثانوي: تقليل حجم الـ head وتخفيف Dropout و L2
    لأن الـ head الضخم مع dropout عالي = تعلم بطيء جداً
    """
    # ── Base Model ────────────────────────────────────────────────────
    base_model = tf.keras.applications.EfficientNetB4(
        include_top=False,
        weights='imagenet',
        input_shape=(380, 380, 3)
    )
    base_model.trainable = False

    # ── Functional API (الحل الصحيح لمشكلة BN) ───────────────────────
    inputs = tf.keras.Input(shape=(380, 380, 3), name="input_image")

    # training=False → BN في base تعمل بـ inference mode دائماً في Phase 1
    x = base_model(inputs, training=False)

    # ── Spatial Aggregation ───────────────────────────────────────────
    x = tf.keras.layers.GlobalAveragePooling2D()(x)
    x = tf.keras.layers.BatchNormalization()(x)

    # ── Block 1: 1024 ─────────────────────────────────────────────────
    x = tf.keras.layers.Dense(
            1024, activation='relu',
            kernel_regularizer=tf.keras.regularizers.l2(1e-5))(x)
    x = tf.keras.layers.BatchNormalization()(x)
    x = tf.keras.layers.Dropout(0.35)(x)

    # ── Block 2: 1024 ─────────────────────────────────────────────────
    x = tf.keras.layers.Dense(
            1024, activation='relu',
            kernel_regularizer=tf.keras.regularizers.l2(1e-5))(x)
    x = tf.keras.layers.BatchNormalization()(x)
    x = tf.keras.layers.Dropout(0.30)(x)

    # ── Block 3: 512 ──────────────────────────────────────────────────
    x = tf.keras.layers.Dense(
            512, activation='relu',
            kernel_regularizer=tf.keras.regularizers.l2(1e-5))(x)
    x = tf.keras.layers.BatchNormalization()(x)
    x = tf.keras.layers.Dropout(0.25)(x)

    # ── Block 4: 512 ──────────────────────────────────────────────────
    x = tf.keras.layers.Dense(
            512, activation='relu',
            kernel_regularizer=tf.keras.regularizers.l2(1e-5))(x)
    x = tf.keras.layers.BatchNormalization()(x)
    x = tf.keras.layers.Dropout(0.20)(x)

    # ── Block 5: 256 ──────────────────────────────────────────────────
    x = tf.keras.layers.Dense(
            256, activation='relu',
            kernel_regularizer=tf.keras.regularizers.l2(1e-5))(x)
    x = tf.keras.layers.BatchNormalization()(x)
    x = tf.keras.layers.Dropout(0.15)(x)

    # ── Block 6: 256 ──────────────────────────────────────────────────
    x = tf.keras.layers.Dense(
            256, activation='relu',
            kernel_regularizer=tf.keras.regularizers.l2(1e-5))(x)
    x = tf.keras.layers.BatchNormalization()(x)
    x = tf.keras.layers.Dropout(0.15)(x)

    # ── Block 7: 128 ──────────────────────────────────────────────────
    x = tf.keras.layers.Dense(
            128, activation='relu',
            kernel_regularizer=tf.keras.regularizers.l2(1e-5))(x)
    x = tf.keras.layers.BatchNormalization()(x)
    x = tf.keras.layers.Dropout(0.10)(x)

    # ── Block 8: 64 ───────────────────────────────────────────────────
    x = tf.keras.layers.Dense(
            64, activation='relu',
            kernel_regularizer=tf.keras.regularizers.l2(1e-5))(x)
    x = tf.keras.layers.BatchNormalization()(x)

    # ── Output ────────────────────────────────────────────────────────
    outputs = tf.keras.layers.Dense(1, activation='sigmoid', name="output")(x)

    model = tf.keras.Model(inputs, outputs, name="FractureNet_B4_Fixed")
    return model, base_model


# Quick preview
model_preview, _ = build_model()
print("📐 Model Architecture:")
print(f"   Total params : {model_preview.count_params():,}")
model_preview.summary()
del model_preview

# =====================================================================
# CELL 6: LOAD DATASETS + AUGMENTATION
# =====================================================================

data_augmentation = tf.keras.Sequential([
    tf.keras.layers.RandomFlip("horizontal_and_vertical"),
    tf.keras.layers.RandomRotation(0.15),
    tf.keras.layers.RandomZoom(0.10),
    tf.keras.layers.RandomContrast(0.10),
    tf.keras.layers.RandomBrightness(0.10),
    tf.keras.layers.RandomTranslation(0.08, 0.08),
], name="augmentation")

train_ds_raw = tf.keras.utils.image_dataset_from_directory(
    train_dir, seed=42, image_size=IMG_SIZE,
    batch_size=BATCH_SIZE, shuffle=True)

val_ds = tf.keras.utils.image_dataset_from_directory(
    val_dir, seed=42, image_size=IMG_SIZE,
    batch_size=BATCH_SIZE, shuffle=False)

test_ds = tf.keras.utils.image_dataset_from_directory(
    test_dir, seed=42, image_size=IMG_SIZE,
    batch_size=BATCH_SIZE, shuffle=False)

train_ds = train_ds_raw.map(
    lambda x, y: (data_augmentation(x, training=True), y),
    num_parallel_calls=tf.data.AUTOTUNE
).prefetch(tf.data.AUTOTUNE)

val_ds  = val_ds.prefetch(tf.data.AUTOTUNE)
test_ds = test_ds.prefetch(tf.data.AUTOTUNE)

print("✅ Datasets ready.")
dataset_stats(train_dir, "Train")
dataset_stats(val_dir,   "Val")
dataset_stats(test_dir,  "Test")

# =====================================================================
# CELL 7: CLASS WEIGHTS
# =====================================================================

fractured_count = len(os.listdir(os.path.join(train_dir, 'Fractured')))
normal_count    = len(os.listdir(os.path.join(train_dir, 'Non_fractured')))
total_train     = fractured_count + normal_count

class_weight = {
    0: (1 / fractured_count) * (total_train / 2.0),
    1: (1 / normal_count)    * (total_train / 2.0)
}
print(f"⚖️  Class weights → 0 (Fractured): {class_weight[0]:.4f} | "
      f"1 (Non_frac): {class_weight[1]:.4f}")

# =====================================================================
# CELL 8: CALLBACKS
# =====================================================================

early_stop = tf.keras.callbacks.EarlyStopping(
    monitor='val_loss', patience=7,
    restore_best_weights=True, verbose=1)

reduce_lr = tf.keras.callbacks.ReduceLROnPlateau(
    monitor='val_loss', factor=0.3,
    patience=3, min_lr=1e-8, verbose=1)

checkpoint = tf.keras.callbacks.ModelCheckpoint(
    filepath=MODEL_PATH,
    monitor='val_accuracy', save_best_only=True, verbose=1)

csv_logger = tf.keras.callbacks.CSVLogger(
    os.path.join(base_path, "training_log.csv"), append=True)

logger_p1 = EpochLogger(phase_name="P1")
logger_p2 = EpochLogger(phase_name="P2")

CALLBACKS_P1 = [early_stop, reduce_lr, checkpoint, csv_logger, logger_p1]
CALLBACKS_P2 = [early_stop, reduce_lr, checkpoint, csv_logger, logger_p2]

print("✅ All callbacks configured.")

# =====================================================================
# CELL 9 — Section 15: Training Phase 1 (20 epochs, base frozen)
# =====================================================================

model, base_model = build_model()

model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-3),  # ← أعلى من قبل
    loss='binary_crossentropy',
    metrics=['accuracy',
             tf.keras.metrics.AUC(name='auc'),
             tf.keras.metrics.Precision(name='precision'),
             tf.keras.metrics.Recall(name='recall')]
)

print("\n" + "="*70)
print("  ⚙️  PHASE 1 — Top-layer training (base frozen)  |  Epochs = 20")
print("  💡 Base model frozen with training=False (fixes BatchNorm bug)")
print("="*70)

history_p1 = model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=EPOCHS,
    class_weight=class_weight,
    callbacks=CALLBACKS_P1,
    verbose=0
)

print("\n✅ Phase 1 complete.")

# =====================================================================
# CELL 10 — Section 16: Fine-Tuning (20 epochs, partial unfreeze)
# =====================================================================

# ✅ في Phase 2: نفعّل base بشكل صريح
base_model.trainable = True

# نجمّد أول 60% من الطبقات (نحافظ على الـ low-level features)
FINE_TUNE_AT = int(len(base_model.layers) * 0.6)
for layer in base_model.layers[:FINE_TUNE_AT]:
    layer.trainable = False

# ✅ مهم: نوقف BN layers في base من التدريب لتجنب تدمير الـ statistics
for layer in base_model.layers:
    if isinstance(layer, tf.keras.layers.BatchNormalization):
        layer.trainable = False

trainable_count = sum(1 for l in base_model.layers if l.trainable)
print(f"🔓 Unfrozen {trainable_count}/{len(base_model.layers)} base layers "
      f"(BN layers kept frozen)")

model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-4),
    loss='binary_crossentropy',
    metrics=['accuracy',
             tf.keras.metrics.AUC(name='auc'),
             tf.keras.metrics.Precision(name='precision'),
             tf.keras.metrics.Recall(name='recall')]
)

print("\n" + "="*70)
print("  🔬 PHASE 2 — Fine-tuning (partial unfreeze)  |  Epochs = 20")
print("="*70)

history_p2 = model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=EPOCHS,
    callbacks=CALLBACKS_P2,
    verbose=0
)

print("\n✅ Phase 2 complete.")
model.save(MODEL_PATH)
print(f"💾 Model saved → {MODEL_PATH}")

# =====================================================================
# CELL 11 — Section 17: Evaluate on Validation Set
# =====================================================================

print("\n" + "="*60)
print("  📋  SECTION 17 — Validation Set Evaluation")
print("="*60)

val_results  = model.evaluate(val_ds, verbose=1)
metric_names = model.metrics_names
print("\n📊 Validation Metrics:")
for name, value in zip(metric_names, val_results):
    print(f"   {name:<15}: {value:.4f}")

# =====================================================================
# CELL 12 — Section 18: Learning Curves
# =====================================================================

def plot_learning_curves(h1, h2):
    def merge(key):
        return h1.history.get(key, []) + h2.history.get(key, [])

    tr_acc  = merge('accuracy');    vl_acc  = merge('val_accuracy')
    tr_loss = merge('loss');        vl_loss = merge('val_loss')
    tr_auc  = merge('auc');         vl_auc  = merge('val_auc')
    tr_prec = merge('precision');   vl_prec = merge('val_precision')
    p1_end  = len(h1.history['loss'])
    epochs_r = range(1, len(tr_acc) + 1)

    # ── جدول كامل ─────────────────────────────────────────────────────
    print("\n" + "="*95)
    print("  📜  SECTION 18 — Full Training Log")
    print("="*95)
    print(f"  {'Ep':<5}|{'Ph':<3}|{'Tr Acc':>8}|{'Vl Acc':>8}|"
          f"{'Tr Loss':>9}|{'Vl Loss':>9}|{'AUC Tr':>7}|{'AUC Vl':>7}|{'Gap':>8}| Status")
    print("-"*95)

    for i in range(len(tr_acc)):
        ph  = "P1" if i < p1_end else "P2"
        gap = tr_acc[i] - vl_acc[i]
        s   = ("🔴 OVERFIT" if gap > 0.10 else
               "🟡 Mild OVF" if gap > 0.05 else
               "🔵 Underfit" if gap < -0.05 else "✅ OK")
        auc_tr = tr_auc[i] if i < len(tr_auc) else 0
        auc_vl = vl_auc[i] if i < len(vl_auc) else 0
        print(f"  {i+1:<5}|{ph:<3}|{tr_acc[i]:>8.4f}|{vl_acc[i]:>8.4f}|"
              f"{tr_loss[i]:>9.4f}|{vl_loss[i]:>9.4f}|"
              f"{auc_tr:>7.4f}|{auc_vl:>7.4f}|{gap:>+8.4f}| {s}")
    print("="*95)

    max_gap = max(a - v for a, v in zip(tr_acc, vl_acc))
    print(f"\n  Overfitting verdict (max gap={max_gap:+.4f}): ", end="")
    if   max_gap > 0.10: print("🔴 Overfitting")
    elif max_gap > 0.05: print("🟡 Mild Overfitting")
    else:                print("🟢 Good — no significant overfitting")

    # ── Plots ─────────────────────────────────────────────────────────
    fig, axes = plt.subplots(2, 2, figsize=(18, 12))
    fig.suptitle('Learning Curves — Training vs Validation',
                 fontsize=17, fontweight='bold')

    def draw(ax, tr, vl, title, ylabel):
        ax.plot(epochs_r, tr, 'o-', color='royalblue',  lw=2, label='Train')
        ax.plot(epochs_r, vl, 'o-', color='darkorange', lw=2, label='Validation')
        ax.axvline(x=p1_end+0.5, color='green', ls='--', lw=1.8,
                   label='Phase-2 start')
        ax.fill_between(epochs_r,
                        [min(a,b) for a,b in zip(tr,vl)],
                        [max(a,b) for a,b in zip(tr,vl)],
                        alpha=0.12, color='crimson', label='Gap')
        ax.set_title(title, fontsize=13, fontweight='bold')
        ax.set_xlabel('Epoch'); ax.set_ylabel(ylabel)
        ax.legend(); ax.grid(True, alpha=0.3)

    draw(axes[0,0], tr_acc,  vl_acc,  'Accuracy',  'Accuracy')
    draw(axes[0,1], tr_loss, vl_loss, 'Loss',      'Loss')
    if tr_auc:  draw(axes[1,0], tr_auc,  vl_auc,  'AUC',       'AUC')
    if tr_prec: draw(axes[1,1], tr_prec, vl_prec, 'Precision', 'Precision')

    plt.tight_layout()
    plt.savefig(os.path.join(base_path, "learning_curves.png"),
                dpi=150, bbox_inches='tight')
    plt.show()
    print("🖼️  Saved → learning_curves.png")


plot_learning_curves(history_p1, history_p2)

# =====================================================================
# CELL 13 — Section 19: Confusion Matrix
# =====================================================================

def get_predictions(ds):
    y_true, y_pred, y_prob = [], [], []
    for imgs, labels in ds:
        probs = model.predict(imgs, verbose=0).flatten()
        y_true.extend(labels.numpy())
        y_pred.extend((probs > 0.5).astype(int))
        y_prob.extend(probs)
    return np.array(y_true), np.array(y_pred), np.array(y_prob)


print("\n" + "="*60)
print("  🔲  SECTION 19 — Confusion Matrix (Validation Set)")
print("="*60)

y_true_val, y_pred_val, y_prob_val = get_predictions(val_ds)
cm = confusion_matrix(y_true_val, y_pred_val)
tn, fp, fn, tp = cm.ravel()

fig, axes = plt.subplots(1, 2, figsize=(16, 6))

sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=CLASS_NAMES, yticklabels=CLASS_NAMES,
            ax=axes[0], linewidths=0.5, annot_kws={"size": 14})
axes[0].set_title('Confusion Matrix — Counts', fontsize=13, fontweight='bold')
axes[0].set_xlabel('Predicted'); axes[0].set_ylabel('Actual')

cm_pct = cm.astype(float) / cm.sum(axis=1, keepdims=True) * 100
sns.heatmap(cm_pct, annot=True, fmt='.1f', cmap='YlOrRd',
            xticklabels=CLASS_NAMES, yticklabels=CLASS_NAMES,
            ax=axes[1], linewidths=0.5, annot_kws={"size": 14})
axes[1].set_title('Confusion Matrix — Normalised (%)', fontsize=13, fontweight='bold')
axes[1].set_xlabel('Predicted'); axes[1].set_ylabel('Actual')

plt.suptitle('Confusion Matrices (Validation Set)', fontsize=15, fontweight='bold')
plt.tight_layout()
plt.savefig(os.path.join(base_path, "confusion_matrix.png"), dpi=150)
plt.show()

print(f"\n  TP={tp} | TN={tn} | FP={fp} | FN={fn}")
print(f"  Sensitivity : {tp/(tp+fn):.4f}")
print(f"  Specificity : {tn/(tn+fp):.4f}")

# =====================================================================
# CELL 14 — Section 20: Classification Metrics
# =====================================================================

print("\n" + "="*60)
print("  📈  SECTION 20 — Classification Metrics (Validation Set)")
print("="*60)
print(classification_report(y_true_val, y_pred_val,
                            target_names=CLASS_NAMES, digits=4))

fpr, tpr, _                       = roc_curve(y_true_val, y_prob_val)
roc_auc                           = auc(fpr, tpr)
precision_curve, recall_curve, _  = precision_recall_curve(y_true_val, y_prob_val)
pr_auc                            = auc(recall_curve, precision_curve)

fig, axes = plt.subplots(1, 2, figsize=(16, 6))
axes[0].plot(fpr, tpr, color='darkorange', lw=2,
             label=f'ROC (AUC={roc_auc:.4f})')
axes[0].plot([0,1],[0,1], 'k--', lw=1)
axes[0].fill_between(fpr, tpr, alpha=0.15, color='darkorange')
axes[0].set_title('ROC Curve', fontsize=13, fontweight='bold')
axes[0].set_xlabel('FPR'); axes[0].set_ylabel('TPR')
axes[0].legend(); axes[0].grid(True, alpha=0.3)

axes[1].plot(recall_curve, precision_curve, color='royalblue', lw=2,
             label=f'PR (AUC={pr_auc:.4f})')
axes[1].fill_between(recall_curve, precision_curve, alpha=0.15, color='royalblue')
axes[1].set_title('Precision-Recall Curve', fontsize=13, fontweight='bold')
axes[1].set_xlabel('Recall'); axes[1].set_ylabel('Precision')
axes[1].legend(); axes[1].grid(True, alpha=0.3)

plt.suptitle('Model Performance Curves', fontsize=15, fontweight='bold')
plt.tight_layout()
plt.savefig(os.path.join(base_path, "roc_pr_curves.png"), dpi=150)
plt.show()
print(f"\n  ROC-AUC={roc_auc:.4f} | PR-AUC={pr_auc:.4f}")

# =====================================================================
# CELL 15 — Section 22: Prediction Function
# =====================================================================

def predict_image(image_path, threshold=0.5, show=True):
    img        = Image.open(image_path).convert('RGB').resize(IMG_SIZE)
    arr        = np.expand_dims(np.array(img, dtype=np.float32), axis=0)
    prob       = float(model.predict(arr, verbose=0)[0][0])
    pred_class = int(prob > threshold)
    label      = CLASS_NAMES[pred_class]
    confidence = prob if pred_class == 1 else 1 - prob

    if show:
        color = 'red' if label == 'Fractured' else 'green'
        plt.figure(figsize=(5, 5))
        plt.imshow(img); plt.axis('off')
        plt.title(f"Prediction: {label}\nProb: {prob:.4f} | Confidence: {confidence:.2%}",
                  fontsize=12, color=color, fontweight='bold')
        plt.tight_layout(); plt.show()

    print(f"\n  🩻 {os.path.basename(image_path)}")
    print(f"  🏷️  Label: {label} | Prob: {prob:.4f} | Conf: {confidence:.2%}")
    return dict(label=label, probability=prob, confidence=confidence)


sample_class = random.choice(CLASS_NAMES)
sample_files = os.listdir(os.path.join(test_dir, sample_class))
if sample_files:
    sample_img = os.path.join(test_dir, sample_class,
                              random.choice(sample_files))
    print(f"\n🔍 Demo: {sample_img}")
    predict_image(sample_img)

# =====================================================================
# CELL 16 — Section 23: Final Test Set Evaluation
# =====================================================================

print("\n" + "="*70)
print("  🧪  SECTION 23 — Final Evaluation on TEST Set")
print("="*70)

test_results = model.evaluate(test_ds, verbose=1)
print("\n📊 Test Metrics:")
for name, value in zip(model.metrics_names, test_results):
    print(f"   {name:<15}: {value:.4f}")

y_true_test, y_pred_test, y_prob_test = get_predictions(test_ds)

print("\n" + "="*50)
print(classification_report(y_true_test, y_pred_test,
                            target_names=CLASS_NAMES, digits=4))

cm_test        = confusion_matrix(y_true_test, y_pred_test)
tn, fp, fn, tp = cm_test.ravel()

fig, axes = plt.subplots(1, 2, figsize=(16, 6))
sns.heatmap(cm_test, annot=True, fmt='d', cmap='Blues',
            xticklabels=CLASS_NAMES, yticklabels=CLASS_NAMES,
            ax=axes[0], linewidths=0.5, annot_kws={"size": 14})
axes[0].set_title('Test CM — Counts', fontsize=13, fontweight='bold')
axes[0].set_xlabel('Predicted'); axes[0].set_ylabel('Actual')

cm_test_pct = cm_test.astype(float) / cm_test.sum(axis=1, keepdims=True) * 100
sns.heatmap(cm_test_pct, annot=True, fmt='.1f', cmap='YlOrRd',
            xticklabels=CLASS_NAMES, yticklabels=CLASS_NAMES,
            ax=axes[1], linewidths=0.5, annot_kws={"size": 14})
axes[1].set_title('Test CM — Normalised (%)', fontsize=13, fontweight='bold')
axes[1].set_xlabel('Predicted'); axes[1].set_ylabel('Actual')

plt.suptitle('Test Set — Confusion Matrices', fontsize=15, fontweight='bold')
plt.tight_layout()
plt.savefig(os.path.join(base_path, "confusion_matrix_test.png"), dpi=150)
plt.show()

fpr_t, tpr_t, _ = roc_curve(y_true_test, y_prob_test)
roc_auc_t       = auc(fpr_t, tpr_t)

plt.figure(figsize=(7, 6))
plt.plot(fpr_t, tpr_t, color='darkgreen', lw=2,
         label=f'Test ROC (AUC={roc_auc_t:.4f})')
plt.plot([0,1],[0,1], 'k--')
plt.fill_between(fpr_t, tpr_t, alpha=0.15, color='darkgreen')
plt.title('ROC Curve — Test Set', fontsize=13, fontweight='bold')
plt.xlabel('FPR'); plt.ylabel('TPR')
plt.legend(); plt.grid(True, alpha=0.3)
plt.savefig(os.path.join(base_path, "roc_test.png"), dpi=150)
plt.show()

print("\n" + "="*50)
print("  ✅  FINAL TEST SUMMARY")
print("="*50)
print(f"  Accuracy    : {test_results[1]:.4f}")
print(f"  AUC         : {roc_auc_t:.4f}")
print(f"  Sensitivity : {tp/(tp+fn):.4f}  (Recall / TPR)")
print(f"  Specificity : {tn/(tn+fp):.4f}  (TNR)")
print(f"  Precision   : {tp/(tp+fp):.4f}")
print(f"  F1-Score    : {2*tp/(2*tp+fp+fn):.4f}")
print("="*50)

# =====================================================================
# CELL 17 — MAIN EXECUTION
# =====================================================================

if __name__ == "__main__":
    print("\n" + "🔷"*35)
    print("  MAIN EXECUTION START")
    print("🔷"*35)

    if not os.path.exists(train_dir):
        print(f"❌ ERROR: '{train_dir}' not found.")
    else:
        standardize_images(train_dir)
        standardize_images(val_dir)
        standardize_images(test_dir)
        balance_dataset(train_dir, target_count=1500)

        if FORCE_RETRAIN and os.path.exists(MODEL_PATH):
            print("⚠️  FORCE_RETRAIN=True — removing old model...")
            os.remove(MODEL_PATH)

        if not os.path.exists(MODEL_PATH):
            print("\n🚀 No saved model — run Cells 6–16 sequentially.")
        else:
            print(f"\n✅ Loading model from {MODEL_PATH}...")
            model = tf.keras.models.load_model(MODEL_PATH)
            model.summary()
            test_ds = tf.keras.utils.image_dataset_from_directory(
                test_dir, seed=42, image_size=IMG_SIZE,
                batch_size=BATCH_SIZE, shuffle=False
            ).prefetch(tf.data.AUTOTUNE)
            y_true_test, y_pred_test, y_prob_test = get_predictions(test_ds)
            print(classification_report(y_true_test, y_pred_test,
                                        target_names=CLASS_NAMES, digits=4))

        print("\n✅ All processes completed successfully.")

# import sys
# !{sys.executable} -m uvicorn app:app --host 127.0.0.1 --port 8000

